# Generated by Django 3.2.7 on 2021-11-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out',
        ),
    ]
