# Generated by Django 3.2.7 on 2021-11-11 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211111_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 12, 12, 14, 14, 384290)),
        ),
    ]
